### ISSUE TITLE
activate travis-ci.org

### ISSUE THREAD

**Issue by jedie** [pypyjs/pypyjs#135]
Since https://github.com/rfk/pypyjs/pull/129 is merged, there is a ".travis.yml" file: https://github.com/rfk/pypyjs/blob/master/.travis.yml

@rfk you only have to activate this repro on https://travis-ci.org/ ;)

**Comment by rfk** [comment]
I *think* I did this correctly with the move to the new org repo:  https://travis-ci.org/pypyjs/pypyjs

**Comment by jedie** [comment]
You have to activate it, because i'm not a project admin:

----
![travis](https://cloud.githubusercontent.com/assets/71315/7902652/463d8480-07c0-11e5-96fb-c24910102201.png)
----

**Comment by rfk** [comment]
I thought I'd put it on the main `pypyjs` repo, but maybe I didn't save properly.  Just went through again and enabled it on all the repos under this org.
