### ISSUE TITLE
No `string` module

### ISSUE THREAD

**Issue by kirbyfan64** [pypyjs/pypyjs#137]
I think it should work under PyPy.js, but it's not in `module_bundler.py`.

**Comment by jedie** [comment]
fork and add it?!? ;)

**Comment by rfk** [comment]
Hmm, `import string` in the pypyjs.org console seems to work OK for me - do you get an error?

**Comment by jedie** [comment]
Yes, it should work, see: https://github.com/rfk/pypyjs/issues/109#issuecomment-104866700

Maybe the importStatementRE-Bug? -> https://github.com/rfk/pypyjs/issues/109#issuecomment-103825389

**Comment by kirbyfan64** [comment]
Maybe...my import statement looks like:

```python
from __future__ import print_function
import re, string, sys
```

I *am* prepending some code to it...maybe that could have an effect?

The JS code is at https://github.com/kirbyfan64/rs/blob/gh-pages/js/load.js.

**Comment by jedie** [comment]
To debug the "importStatementRE", add code like this: https://github.com/rfk/pypyjs/issues/109#issuecomment-104293782

**Comment by jedie** [comment]
Hm. confirm the bug:

http://i.snag.gy/LMpf5.jpg

**Comment by kirbyfan64** [comment]
Definitely shows that the `import` regex is eating up too much stuff. I'm pretty sure it has something to do with `\s` matching newlines.

My hack-y, temporary fix was to change:

```javascript
var submods = match[0].split("import")[1];
```

to:

```javascript
var submods = match[0].split("import")[1].split('\n')[0];
```

**Comment by jedie** [comment]
No RE expert here?!?

**Comment by kirbyfan64** [comment]
@jedie I tried to fix it but failed. I can take another shot at it, though.

**Comment by jedie** [comment]
I also tried in the past and failed... But i'm not a RE-Hacker ;)

**Comment by kirbyfan64** [comment]
@jedie I kind of [am](https://github.com/kirbyfan64/rs)(in fact, my use of PyPy.js is for a web interface to mey regex text replacement tool), but that darn thing is really long...

**Comment by jedie** [comment]
https://github.com/pypyjs/pypyjs/issues/150 will fix this. See: https://github.com/pypyjs/pypyjs/issues/150#issuecomment-116744738

So i will close this issues.
