### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jedie** [pypyjs/pypyjs#139]
A LICENSE file is missing and i didn't found many information about the license status of this project.

**Comment by kirbyfan64** [comment]
https://github.com/pypyjs/pypyjs/blob/master/LICENSE.txt

It's there.

**Comment by jedie** [comment]
Oh! :flushed:

It's MIT, isn't it?

**Comment by rfk** [comment]
I added a note to the readme in https://github.com/pypyjs/pypyjs/commit/1649999014a59fe2ea1dccf98b5d86dcadf365ac :-)
