### ISSUE TITLE
add unittests with 'spidermonkey'...

### ISSUE THREAD

**Issue by jedie** [pypyjs/pypyjs#141]
It seems that there are only two out-dated packages available:
* https://pypi.python.org/pypi/python-spidermonkey/ last release from: 2011-02-17
* https://pypi.python.org/pypi/pydermonkey/ last release from: 2009-09-11

Maybe a better idea is to use selenium with a minimal webpage and the heavy usage of **webdriver.execute_script()** ?

**Comment by rfk** [comment]
I was thinking of just running them directly in the spidermonkey command-line shell, i.e. plain javascript tests without a python runner around them.  But it's probably too much hassle to be worth setting that up, and a combination of running under nodejs shell and in a browser via selenium will give pretty solid coverage.
