### ISSUE TITLE
Use WebAssembly in the future.

### ISSUE THREAD

**Issue by IronManMark20** [pypyjs/pypyjs#146]
I was scrolling through /r/python when I read [this interesting article](http://techcrunch.com/2015/06/17/google-microsoft-mozilla-and-others-team-up-to-launch-webassembly-a-new-binary-format-for-the-web/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29). Essentially, WebKit will begin supporting binary blobs of C/C++ code. Therefore, I think PyPyJS should use WebAssembly, once it releases (still pre-release). To quote the article:

> it’s much faster for the engine to decode the binary format (up to 23x faster in the current prototype) than parsing asm.js code, for example.

A 23x speedup sounds pretty nice to me, and we are already generating C++ files from the rpython bit, right?

And finally, it won't require much porting (taken from the article):
>and developers will be able to use the same Emscripten tool for WebAssembly as they use for compiling asm.js code today

All in all, good news! Do you think PyPyJS will target WebAssembly?

**Comment by kirbyfan64** [comment]
This was already opened: #145.

**Comment by jedie** [comment]
Think there are some nice information. So i copy&paste it to https://github.com/pypyjs/pypyjs/issues/145#issuecomment-113192334 and will close this here...

**Comment by kirbyfan64** [comment]
> A 23x speedup sounds pretty nice to me, and we are already generating C++ files from the rpython bit, right?

`s/C++/C/`
