### ISSUE TITLE
findImportedNames only matches the first import

### ISSUE THREAD

**Issue by MaximeCheramy** [pypyjs/pypyjs#150]
When I exec a file that begins with something like that:

    from mymodule.foo import bar
    from mymodule.secondfoo import hello

Only the first module is loaded. The reason is that the regexp matches "bar\n    from mymodule.secondfoo import hello".

In order to fix this issue, I have done the following:

    diff --git a/lib/pypy.js b/lib/pypy.js
    index 6fa7fbb..931221e 100644
    --- a/lib/pypy.js
    +++ b/lib/pypy.js
    @@ -730,7 +730,7 @@ PyPyJS.prototype._repl_loop = function _repl_loop(prmpt, ps1) {
     // XXX TODO: this is far from complete and should not be done with a regex.
     // Perhaps we can call into python's "ast" module for this parsing?
     //
    -var importStatementRE = /(from\s+([a-zA-Z0-9_\.]+)\s+)?import\s+\(?\s*([a-zA-Z0-9_\.\*]+(\s+as\s+[a-zA-Z0-9_]+)?\s*,?\s*)+\s*\)?/g
    +var importStatementRE = /(from\s+([a-zA-Z0-9_\.]+)\s+)?import\s+\(?\s*([a-zA-Z0-9_\.\*]+(\s+as\s+[a-zA-Z0-9_]+)?[ \t]*,?[ \t]*)+[ \t]*\)?/g
     PyPyJS.prototype.findImportedNames = function findImportedNames(code) {
       var match = null;
       var imports = [];

I know this function should be rewritten but meanwhile this allows my code to work...

**Comment by jedie** [comment]
This RE is not good working, see also: https://github.com/pypyjs/pypyjs/issues/137

Maybe your RE is better?!?

**Comment by rfk** [comment]
Ah, so the `\s` in the regex is matching past the newline?  I guess I brought too much of my python-regex knowledge over to javascript, thanks @MaximeCheramy

**Comment by MaximeCheramy** [comment]
The `\s` matches the line break yes. More specifically, it matches: `[ \f\n\r\t\v​\u00a0\u1680​\u180e\u2000​\u2001\u2002​\u2003\u2004\u2005\u2006​\u2007\u2008​\u2009\u200a​\u2028\u2029​\u202f\u205f​\u3000]`

**Comment by jedie** [comment]
OK, i test the new re with in pypyjs-release and remove all the work-a-round in the tests with:

* https://github.com/pypyjs/pypyjs-release/commit/0f299181936c1a37b3b3e4440a747fd6652f9a52
* https://github.com/pypyjs/pypyjs.github.io/commit/6be03c5456a3dcfa2b21b76c2f1d31d5a7380cc2

It looks good:

https://travis-ci.org/pypyjs/pypyjs.github.io/builds/68835622
