### ISSUE TITLE
speeding up the loading time

### ISSUE THREAD

**Issue by girishramnani** [pypyjs/pypyjs#153]
could the speed to load be increased by removing some of the modules.

**Comment by jedie** [comment]
Yes, startup- and "import python module"- time needs enhancement.

Please, look into these "threads":
* https://github.com/pypyjs/pypyjs.github.io/issues/4
* https://github.com/pypyjs/pypyjs.github.io/issues/7

(...a bad idea to spread the issues :( But this is my fault...)
