### ISSUE TITLE
How to convert Unit8Array to a Python's StringIO?

### ISSUE THREAD

**Issue by chfw** [pypyjs/pypyjs#171]
My use case is to download a binary file using ajax  from localhost. So I followed this [binary ajax call example ](https://github.com/henrya/js-jquery/blob/master/BinaryTransport/demos/example.html) 

Here is the original script:

```
file_content = null;
file_type = null;

var get_file = function(file_url, callback){
    var content;
    $.ajax({
        url: file_url,
        type: "GET",
        dataType: "binary",
        responseType: "arraybuffer",
        processData: false,
        async:false,
        success: function(result, a, xhr){
            file_content = result;
            file_type = xhr.getResponseHeader('content-type');
        },
        error: function (xhr, ajaxOptions, thrownError) {
            console.log(xhr.status);
            console.log(thrownError);
        }
    });
};
```

Here's the whole story:

```
Welcome to PyPy.js!
>>> import js
>>> getter=js.globals['get_file']
>>> getter('sample-data.xls',None)
>>> x=js.eval("new Uint8Array(file_content)")
>>> print x
[object Uint8Array]
>>> x[0]
<js.Number 208.000000>
>>> x.length
<js.Number 6656.000000>
>>> dir(x)
[<js.String '0'>, <js.String '1'>,...]
```

The question is: **how to convert it to a normal Python's StringIO?**

Why Uint8Array? because I could not get anything out of arraybuffer

```
>>> y=js.globals['file_content']
>>> print y
[object ArrayBuffer]
>>> y[1]
<js.Undefined>
>>> dir(y)
[]
```

**Ultimately, I would like to have the file content in pypyjs**, please also let me if there is a better way.

**Comment by kirbyfan64** [comment]
Did you try `list(x)`?

**Comment by kirbyfan64** [comment]
Try something like:

```python
import js

getter = js.globals['get_file']
getter('sample-data.xls', None)
x = js.new(js.globals['Uint8Array'], js.globals['file_content'])
# x is our Uint8Array.
print x
# Convert it to a list.
print list(x)
```

**Comment by chfw** [comment]
Got a list but its content is not what I wanted.

    Welcome to PyPy.js!
    >>> import js
    >>> getter=js.globals['get_file']
    >>> getter('sample-data.xls', None)
    <js.Undefined>
    >>> x=js.eval("new Uint8Array(file_content)")
    >>> y=list(x)
    >>> print y
    [<js.String '0'>, <js.String '1'>, <js.String '2'>,...
    >>>

**Comment by chfw** [comment]
for people who is interested to help, here the reproducing environment:

    git clone https://github.com/chfw/pypyjs-release.git
    cd pypyjs-release
    python -m SimpleHTTTPServer

Then in your browser, type in http://localhost:8000 and type in the script in this issue.

**Comment by xubiuit** [comment]
is there any updates, guys?

**Comment by rfk** [comment]
I'm sorry to say, this project is no longer actively maintained so I would not expect further updates here: https://github.com/pypyjs/pypyjs/issues/213

**Comment by HoverHell** [comment]
For the record, in case anyone tries this in pypyjs or an equivalent project: `list(uint8array_obj)` returns a list of js.String; however, `uint8array_obj[0]` returns a js.Number; therefore, `bytes(bytearray([int(uint8array_obj[idx]) for idx in range(uint8array_obj.length)]))` converts that object to py's `bytes`.
