### ISSUE TITLE
Nuitka

### ISSUE THREAD

**Issue by datnamer** [pypyjs/pypyjs#176]
http://nuitka.net/pages/overview.html
http://podcastinit.com/kay-hayen-nuitka.html
Does that help in any way?

**Comment by kirbyfan64** [comment]
I don't think Nuitka even works with PyPy, so...probably not...

**Comment by datnamer** [comment]
It doesn't work with cpython eithe IIRC... it is supposed to replace the interpreter, with compilation to c++. Then maybe it could go to llvm then emscripten...and not have to ship the whole  interpreter.

Its already faster than cpython on provided benchmarks.

**Comment by kirbyfan64** [comment]
> It doesn't work with cpython eithe IIRC...

But it depends on running under CPython.

**Comment by rfk** [comment]
Thanks for the links @datnamer, Nuitka is indeed an interesting project.  I think it would be a lot of fun to try an emscripten/asmjs backend for Nuitka, as an alternative way of putting a python app into the browser.  Do let us know if you give it a try!

However, I think it would be an entirely separate project and not able to re-use much for pypyjs, so I'm going to close this issue out.
