### ISSUE TITLE
Add module documentation unclear / possibly broken

### ISSUE THREAD

**Issue by orionz** [pypyjs/pypyjs#179]
I'm trying to follow the documentation to add a module to pypyjs.  It isn't clear from the docs at what stage in the process I should be using the module_bundler.  Here is my current build script (which takes many hours to run so fast experimentation is out of the question - thus I'm here asking for help).

```bash
#!/bin/bash -x
git clone https://bitbucket.org/pypy/numpy.git
git clone git@github.com:pypyjs/pypyjs.git
cd pypyjs
git submodule init
git submodule update
npm install
pypy ./tools/module_bundler.py add ./lib/modules ../numpy/
sudo make
make dist
```

The resulting `pypyjs-0.4.1.tar.gz` does not seem to contain numpy as `import numpy` fails.  Looking through the Makefile I think it's getting deleted here.

```
./lib/pypyjs.vm.js: ./build/pypyjs.vm.js
        cp ./build/pypyjs.vm.js ./lib/
        python ./tools/extract_memory_initializer.py ./lib/pypyjs.vm.js
        python ./tools/compress_memory_initializer.py ./lib/pypyjs.vm.js
        rm -rf ./lib/modules/   <--------- HERE
        python tools/module_bundler.py init ./lib/modules/
```

As this `./lib/modules` folder being deleted had numpy in it.

**Comment by rfk** [comment]
I guess you may have figured this out since you closed the issue, but noting for future reference: the build pypyjs bundle include a copy of the module_bundler.py script, which you can use to add/remove modules to it after it's been built.

Doing this step:

> pypy ./tools/module_bundler.py add ./lib/modules ../numpy/
 
later in the build process will probably have the same effect
