### ISSUE TITLE
How do I pass JSON into pypyjs?

### ISSUE THREAD

**Issue by bioball** [pypyjs/pypyjs#181]
I'm trying to pass some stringified JSON into pypyjs, and want to coerce this into a dictionary. How do I do this?

I've tried parsing the JSON on the JavaScript side first, then passing it into python, and end up with a `js.Object`. I've also tried passing in the string into python, and using the `json` module to parse it, but I get this error: `Uncaught TypeError: expected string, got String object`

I feel like I'm missing something obvious here...

**Comment by rfk** [comment]
Hi @bioball, you could try coercing the value from a javascript string to a python string like this:

```
json.loads(str(the_string_object_you_passed_in_from_javascript))
```

The reason for the `Uncaught TypeError: expected string, got String object` error is that there's currently no automatic coercion between javascript objects and python objects.  Instances of `js.String` are references to strings that live in the javascript VM; doing `str()` on them copies them into native python strings.

(I'd like to figure out a way to automate some of this coercion, especially for immutable types like strings.  But I haven't figured out enough details yet.)

**Comment by bioball** [comment]
Ah, thanks! That worked.

**Comment by ShaneFarrell** [comment]
@rfk Typically things in python aren't coerced and instead rely on duck typing. All you need to do is add the same methods to js.String as the inbuilt string has and make it inherit from the correct ABCs. One of the biggest changes that was introduced in Python 3 was to remove automatic conversion between unicode and str. I'm sure there are plenty of examples of how to make builtin type substitutes. Though this begs the question of why JS versions of the builtin types are needed at all (though I'm sure there's some reason).
