### ISSUE TITLE
create new Oblect

### ISSUE THREAD

**Issue by artyprog** [pypyjs/pypyjs#186]
Hello,

How can I create an instance from a javascript 'class'
myobj = new MyObj()

regards

**Comment by artyprog** [comment]
I created a global Javascript function  which does the Job...
You van close the issue

Regards

**Comment by rfk** [comment]
Hi @artyprog, you can also use `js.new` to invoke javascript constructors, like this:

```
>>> a = js.new(js.globals.Array, 1, 2, 3)
>>> print a
1,2,3,
>>> 
```

**Comment by artyprog** [comment]
Thank you Ryan.

PyPyJS fits totally my needs :-)

http://salvatore.diodev.fr/pypybox

**Comment by rfk** [comment]
This is very cool, thanks for sharing! :-)

**Comment by artyprog** [comment]
Thank you :-)
In fact, I would like PyPyBox  to be an alternative platform to ProcessingJS.

I am hesitatiing between the best javascript library to include in PyPyBox :
ProcessingJS, P5JS, PixiJS....

If you have any suggestions for enhancing PyPyBox i would be very glad :-)

**Comment by jedie** [comment]
I add a link to PyPyBox here: https://github.com/pypyjs/pypyjs-examples#links

**Comment by artyprog** [comment]
Nice, that is very encouraging :-)

2016-03-22 11:17 GMT+01:00 Jens Diemer <notifications@github.com>:
