### ISSUE TITLE
Any thoughts of webassembly

### ISSUE THREAD

**Issue by Serkan-devel** [pypyjs/pypyjs#201]
There is a project to run compiled code on a browser called <a href="http://webassembly.org/">webassembly</a>.

It can run C/C++ in a sandbox, is faster to run and has a smaller file size.

This currently only works on beta builds on all major browsers but it might be worth it for faster downloads and higher performance.

It would be nice to have a pypy.wasm project that utilizes webassembly while still maintaining pypy.js as a fallback option, when it isn't supported.

And besides, is this project still active?

**Comment by rfk** [comment]
I've been keeping an eye on webassembly and starting to teach myself more about it by working on a little polyfill: https://github.com/rfk/wasm-polyfill

I haven't tried porting pypyjs to it in any serious way yet though.  If you're interested in trying I'd be happy to suggest a few places to start.

>  is this project still active?

Unfortunately I haven't been able to make much time for the project lately, although I'm certainly still interested in this space and in pushing it forward.

**Comment by jedie** [comment]
We have: https://github.com/pypyjs/pypyjs/issues/145 (So this can be closed, isn't it?)
