### ISSUE TITLE
Closing Writable '/dev/null' Crashes Interpreter

### ISSUE THREAD

**Issue by jvantuyl** [pypyjs/pypyjs#82]
Title says it all.  This only seems to happen to me with a writable file object.  Reproduce with:

```
with open('/dev/null', 'w') as f:
    f.write('foo')
```

I was able to reproduce this with:
- Chrome 42.0.2311.90 (live-locks, only impacts tab)
- FireFox 23.0.1 (kills whole browser before complaining about unresponsive script)
- FireFox 36.0.4 (kills whole browser before complaining about unresponsive script)
- FireFox 37.0.2 (kills whole browser before complaining about unresponsive script)

All of these were on a 64-bit Intel Mac.

**Comment by rfk** [comment]
I can confirm this locally, it locks up the whole of firefox.  No idea what it's doing but at least it's reproducible.  Thanks for the report!

**Comment by rfk** [comment]
AFAICT this is an upstream issue in emscripten: https://github.com/kripken/emscripten/pull/3454

**Comment by jvantuyl** [comment]
Looks very fixed.
